- name: Installing chaotic-aur repos.
  become: true
  shell: |
      pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
      pacman-key --lsign-key 3056513887B78AEB 
      pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
  tags:
    - aur
    - install

- name: Configure pacman for chaotic-aur
  become: true
  blockinfile:
    path: /etc/pacman.conf 
    block: |
      [chaotic-aur]
      Include = /etc/pacman.d/chaotic-mirrorlist
  tags:
    - aur
    - install

- name: Update pacman cache
  become: true
  pacman:
    update_cache: yes
  tags:
    - aur

- name: Installing paru - AUR helper
  become: true
  pacman:
    name:
      - paru
  tags:
    - aur

- name: Disable password for paru
  become: true
  lineinfile:
    path: /etc/sudoers
    line: 'sdk ALL=(ALL) NOPASSWD: /usr/bin/paru'
  tags: 
    - aur
